### ISSUE TITLE
Program stops working

### ISSUE THREAD

**Issue by adamhyman** [adamhyman/dinar-trader#12]
![image](https://user-images.githubusercontent.com/1277113/27756640-259db9ca-5dae-11e7-9c42-7f58d897532d.png)

**Comment by bustoutfunk** [comment]
That looks like a connection issue (i.e. your Wifi sent out or the server didn't respond). I don't think this is an issue. If you see it again please reopen this issue.

**Comment by bustoutfunk** [comment]
@adamhyman, I am getting a different problem but mine is also constantly crashing:
![image](https://user-images.githubusercontent.com/7535593/27773360-d86bf6f0-5f2c-11e7-85d3-69c84eec8b1b.png)

It could be we are pinging the server too often. I'll play around with the delay.

**Comment by bustoutfunk** [comment]
Resolved with longer delay.

**Comment by bustoutfunk** [comment]
Nevermind, I even did 60 seconds. I'll have to investigate.

**Comment by bustoutfunk** [comment]
120 seconds seems to be working but will test further and report back.

**Comment by bustoutfunk** [comment]
@adamhyman I ran this for about 2 hours and it did not crash. Please test out 233eb4b. If it works for you then I would like to open a pull request to merge develop into master.

Additionally, once you have verified that the current code works please close out this issue.

**Comment by bustoutfunk** [comment]
It still crashed for me...:disappointed: 

I wrapped a try-except statement around the "get_balances" function so anytime ANY type of error occurs you will see this output:

```
Caught this error:
504
Restarting loop.
```
For example:
```
Getting prices.
Caught this error:
504
Restarting loop.
Getting prices.
Kraken Bid:  276.84856735
Kraken Ask:  279.133234362
Gemini Bid:  277.60425000000004
Gemini Ask:  279.025825
```
This, however, can be very dangerous as if some unknown error occurs it will just continue to trade. We may want the program to stop on any unknown error. I tried to handle just the HTTP 504 error but couldn't get it to work. The biggest issue is that I need to be able to replicate that error consistently in order to debug it. It happens once in a blue moon. I'll have to investigate. In the mean time d895b16 should work for us for now...

**Comment by bustoutfunk** [comment]
Note to self: Need to add try-catch for transactions as well

```
Getting prices.
Kraken Bid:  278.930998914
Kraken Ask:  282.32883136799995
Gemini Bid:  278.392275
Gemini Ask:  279.79775

No opportunities found. Sleeping for 15 seconds.

Getting prices.
Kraken Bid:  279.77070997399994
Kraken Ask:  282.326004036
Gemini Bid:  278.392275
Gemini Ask:  279.79775

No opportunities found. Sleeping for 15 seconds.

Getting prices.
Kraken Bid:  279.87044000000003
Kraken Ask:  282.325532814
Gemini Bid:  278.392275
Gemini Ask:  279.79775

Buying on Gemini, Selling on Kraken
{'avg_execution_price': '279.10', 'options': [], 'type': 'exchange limit', 'side': 'buy', 'is_cancelled': False, 'timestampms': 1499057
381400, 'was_forced': False, 'remaining_amount': '0', 'price': '1000.00', 'client_order_id': 'immediate-or-cancel', 'is_live': False, '
timestamp': '1499057381', 'original_amount': '0.001', 'is_hidden': False, 'exchange': 'gemini', 'order_id': '865545629', 'id': '8655456
29', 'executed_amount': '0.001', 'symbol': 'ethusd'}
{'result': {'txid': ['OHEDKX-WOAPI-HTRNNQ'], 'descr': {'order': 'sell 0.00100000 ETHUSD @ market'}}, 'error': []}
Transactions Complete
Kraken USD: 29.1999
Kraken ETH: 10.9876497600
Kraken BTC: 0.0500000000
Gemini USD: 3175.25
Gemini ETH: 0.008
Gemini BTC: 0
No opportunities found. Sleeping for 15 seconds.

Getting prices.
Kraken Bid:  279.870569662
Kraken Ask:  282.32547265799997
Gemini Bid:  278.392275
Gemini Ask:  279.79775

Buying on Gemini, Selling on Kraken
{'avg_execution_price': '279.10', 'options': [], 'type': 'exchange limit', 'side': 'buy', 'is_cancelled': False, 'timestampms': 1499057
423557, 'was_forced': False, 'remaining_amount': '0', 'price': '1000.00', 'client_order_id': 'immediate-or-cancel', 'is_live': False, '
timestamp': '1499057423', 'original_amount': '0.001', 'is_hidden': False, 'exchange': 'gemini', 'order_id': '865546749', 'id': '8655467
49', 'executed_amount': '0.001', 'symbol': 'ethusd'}
{'result': {'txid': ['O7UH5S-CV3HU-Q3AAJM'], 'descr': {'order': 'sell 0.00100000 ETHUSD @ market'}}, 'error': []}
Transactions Complete
Kraken USD: 29.4798
Kraken ETH: 10.9866497600
Kraken BTC: 0.0500000000
Gemini USD: 3174.97
Gemini ETH: 0.009
Gemini BTC: 0
No opportunities found. Sleeping for 15 seconds.

Getting prices.
Kraken Bid:  279.87044000000003
Kraken Ask:  282.325462632
Gemini Bid:  278.392275
Gemini Ask:  279.79775

Buying on Gemini, Selling on Kraken
{'avg_execution_price': '279.10', 'options': [], 'type': 'exchange limit', 'side': 'buy', 'is_cancelled': False, 'timestampms': 1499057
459535, 'was_forced': False, 'remaining_amount': '0', 'price': '1000.00', 'client_order_id': 'immediate-or-cancel', 'is_live': False, '
timestamp': '1499057459', 'original_amount': '0.001', 'is_hidden': False, 'exchange': 'gemini', 'order_id': '865549126', 'id': '8655491
26', 'executed_amount': '0.001', 'symbol': 'ethusd'}
Traceback (most recent call last):
  File "exchange_query.py", line 62, in <module>
    print(kraken.session.query_private('AddOrder', {'pair': 'XETHZUSD', 'type': 'sell', 'ordertype': 'market', 'price': '20', 'volume':
 '.001'}))
  File "C:\Users\amahpour\dinar-trader\python3-krakenex\krakenex\api.py", line 194, in query_private
    return self._query(urlpath, req, conn, headers)
  File "C:\Users\amahpour\dinar-trader\python3-krakenex\krakenex\api.py", line 137, in _query
    ret = conn._request(url, req, headers)
  File "C:\Users\amahpour\dinar-trader\python3-krakenex\krakenex\connection.py", line 93, in _request
    raise http.client.HTTPException(response.status)
http.client.HTTPException: 504
```

**Comment by bustoutfunk** [comment]
@adamhyman I've added a better handler for this error but only for when we check prices.

In the previous comment I showed how an actual trade can fail and not go through because of the HTTP 504 error. If that is the case you will end up selling/buying on Gemini but make no trade on Kraken. That, to me, can become a very serious problem.

I've been searching through the net to find out more about the Kraken HTTP 504 error but couldn't find anything. The HTTP 504 error is just a standard [gateway timeout error](https://www.lifewire.com/504-gateway-timeout-error-explained-2622941). I'm assuming it's just Kraken not responding either in time or at all but not sure why. As far as my calculations go we are well within the [API call rate](https://support.kraken.com/hc/en-us/articles/206548367-What-is-the-API-call-rate-limit-) so I'm very perplexed by the HTTP 504 error.

I really think we need to resolve this before going live with this code. Any thoughts?

**Comment by bustoutfunk** [comment]
@adamhyman, the only workaround I see for now (until we understand the HTTP 504 error completely) is to modify the buy/sell sequence to the following:

```
# Perform transaction on Kraken exchange first (regardless of a sell or buy). 
if (Kraken transaction reports a success):
    # Proceed with Gemini transaction
else:
    # Sleep for 15 seconds and restart loop

What do you think?

**Comment by bustoutfunk** [comment]
@adamhyman, I went ahead and implemented the logic that I posted in the last comment. Everything seems to be working pretty smoothly. Will test for a few hours and report back.

**Comment by bustoutfunk** [comment]
Got a new error:
```
Traceback (most recent call last):
  File "exchange_query.py", line 50, in <module>
    k_trade_info = kraken.get_trade_info("ETHUSD")
  File "C:\Users\amahpour\dinar-trader\exchange_session.py", line 84, in get_trade_info
    k_ticker = self.session.query_public('Ticker',{'pair': self.get_pair_name("ETHUSD")})['result']
  File "C:\Users\amahpour\dinar-trader\python3-krakenex\krakenex\api.py", line 157, in query_public
    return self._query(urlpath, req, conn)
  File "C:\Users\amahpour\dinar-trader\python3-krakenex\krakenex\api.py", line 137, in _query
    ret = conn._request(url, req, headers)
  File "C:\Users\amahpour\dinar-trader\python3-krakenex\krakenex\connection.py", line 90, in _request
    response = self.conn.getresponse()
  File "C:\Python35\lib\http\client.py", line 1174, in getresponse
    response.begin()
  File "C:\Python35\lib\http\client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "C:\Python35\lib\http\client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python35\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Python35\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python35\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "C:\Python35\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by bustoutfunk** [comment]
Added an exception handler for socket error in 4ff6025. Testing now.

**Comment by bustoutfunk** [comment]
Seems to be working now. Closing issue.
