### ISSUE TITLE
Error causing program to stop running.

### ISSUE THREAD

**Issue by adamhyman** [adamhyman/dinar-trader#19]
This error caused the program to stop running.  I was running in IDLE at the time.

![image](https://user-images.githubusercontent.com/1277113/27901193-faecb9d8-61e5-11e7-98d5-e3b6342be0f7.png)

Here's the text of the error:

```
2017-07-06 00:51:51,846 - root - INFO - Getting prices.
2017-07-06 00:51:56,170 - root - INFO - Kraken Bid:  269.806693948
2017-07-06 00:51:56,232 - root - INFO - Kraken Ask:  271.70459999999997
2017-07-06 00:51:56,248 - root - INFO - Gemini Bid:  269.56440000000003
2017-07-06 00:51:56,248 - root - INFO - Gemini Ask:  270.92562499999997
2017-07-06 00:51:56,263 - root - INFO - 
2017-07-06 00:51:56,263 - root - INFO - No opportunities found. Sleeping for 15 seconds.
2017-07-06 00:52:11,282 - root - INFO - 
2017-07-06 00:52:11,282 - root - INFO - Getting prices.
Traceback (most recent call last):
  File "C:\Users\ahyman\Dropbox\Crypto\dinar-trader\exchange_query.py", line 55, in <module>
    k_trade_info = kraken.get_trade_info("ETHUSD")
  File "C:\Users\ahyman\Dropbox\Crypto\dinar-trader\exchange_session.py", line 86, in get_trade_info
    k_ticker = self.session.query_public('Ticker',{'pair': self.get_pair_name("ETHUSD")})['result']
  File "C:\Users\ahyman\Dropbox\Crypto\dinar-trader\python3-krakenex\krakenex\api.py", line 157, in query_public
    return self._query(urlpath, req, conn)
  File "C:\Users\ahyman\Dropbox\Crypto\dinar-trader\python3-krakenex\krakenex\api.py", line 137, in _query
    ret = conn._request(url, req, headers)
  File "C:\Users\ahyman\Dropbox\Crypto\dinar-trader\python3-krakenex\krakenex\connection.py", line 89, in _request
    self.conn.request('POST', url, data, headers)
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\ahyman\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:748)
>>> 
```

**Comment by adamhyman** [comment]
I think it's because it lost internet connection.

**Comment by bustoutfunk** [comment]
That would make sense. I'd recommend running an overnight test on my sever and report back.

**Comment by bustoutfunk** [comment]
@adamhyman, any luck?

**Comment by bustoutfunk** [comment]
@adamhyman, update?

**Comment by adamhyman** [comment]
I haven't seen it for a while.  I'm closing the issue.
