### ISSUE TITLE
JSON key error

### ISSUE THREAD

**Issue by bustoutfunk** [adamhyman/dinar-trader#26]
Need to _except_ this error:
```
Traceback (most recent call last):
  File "C:\Users\Ari-Server\dinar-trader\exchange_query.py", line 99, in <module>
    k_trade_info = kraken.get_trade_info("ETHUSD")
  File "C:\Users\Ari-Server\dinar-trader\exchange_session.py", line 105, in get_trade_info
    k_ticker = self.session.query_public('Ticker',{'pair': self.get_pair_name("ETHUSD")})['result']
  File "C:\Python36\lib\site-packages\krakenex\api.py", line 148, in query_public
    return self._query(urlpath, req, conn)
  File "C:\Python36\lib\site-packages\krakenex\api.py", line 131, in _query
    return json.loads(ret)
  File "C:\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bustoutfunk** [comment]
This is another HTTP timeout related error. Only this time we just get an empty JSON object so the code dies when asking for the 'result' key.

**Comment by adamhyman** [comment]
Can we check if the JSON object is empty?  So the code doesn't stop running?

**Comment by bustoutfunk** [comment]
Done. Closing issue. Please re-open if problem persists.
